---
- hosts: all
  become: true
  vars:
    moto: Hello user!
  tasks:
    - name: Change /etc/motd
      copy:
        content: "{{ moto }}"
        dest: /etc/motd
        owner: root
        group: root
        mode: 0644
...